site_name: MicroSoft Excel Pivot Table Tutorial
nav:
  - Home: "index.md"
  - Creating a Pivot Table: "/creating-pivot-tables"
  - Customizing a Pivot Table: "/customizing-pivot-tables/"
  - Installing Express: "/visualizing-data/"
  - Troubleshooting: "/troubleshooting/"
  - Glossary: "/glossary/"

repo_url: https://github.com/DanielOkonov/User-Guide

repo_name: DanielOkonov/User-Guide

theme:
  name: material
  features:
    # - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

icon:
  repo: fontawesome/brands/git-alt

extra:
  social:
    # - icon: fontawesome/brands/github-alt
    #   link: https://github.com/am-eskandari
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/am.eskandari
    # - icon: fontawesome/brands/linkedin
    #   link: https://www.linkedin.com/in/am-eskandari/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/am-eskandari"  target="_blank" rel="noopener">Amir Eskandari</a>
  &copy; 2023 <a href="https://github.com/DanielOkonov"  target="_blank" rel="noopener">Daniel Okonov</a>
